#+TITLE: org-pdftools: a custom org link type for pdf-tools

This project was inspired by and built upon ~org-pdfview~ from @markus1189.
* Installation

You can now install ~org-pdftools~ and ~org-noter-pdftools~ from MELPA!
[[https://melpa.org/#/org-pdftools][file:https://melpa.org/packages/org-pdftools-badge.svg]]
* Usage

#+BEGIN_SRC elisp
(use-package org-pdftools
  :config (setq org-pdftools-root-dir /path/you/store/pdfs
                org-pdftools-search-string-separator "??")
  (with-eval-after-load 'org
    (org-link-set-parameters "pdftools"
                             :follow #'org-pdftools-open
                             :complete #'org-pdftools-complete-link
                             :store #'org-pdftools-store-link
                             :export #'org-pdftools-export)
    (add-hook 'org-store-link-functions 'org-pdftools-store-link)))

(use-package org-noter-pdftools
  :after (org-noter))
#+END_SRC

* Current features
The provided function includes:
- [X] (Sort-of) backward compatibility with org-pdfview: simply change the link prefix from
  ~pdfview:~ to ~pdftools:~.
- [X] The reason this URL prefix change was proposed is that ~pdftools:~ links can
  also point to ~pdf-occur~ searchs. Multi-file search is also supported.
- [X] There is also support for ~pdf-isearch~.
- [X] Beyond the original link implementation that stores only file path and page
  number, now you can store the precise location of annotations.
- [X] If there are selected texts on the current PDF page, it will be ~marked-up~
  using pdf-tools markup functions (by default, underline) automatically and the
  corresponding annotation id is stored in the link.

* Integration with ~org-noter~
You can use the vanilla ~org-noter~ now.

- [X] Integrate with ~org-noter~, such that ~org-noter~ can remember the precise
  location (in the resolution of the exact annotation).
- [X] Jump from a PDF annotation to a associated org-heading ~org-noter-sync-*~ and
  ~org-noter-jump-to-heading~.
- [X] Transform old org-noter notes to newer ones and sync with the corresponding
  PDF. ~org-noter-convert-old-notes~
- [-] PDF annotation will have full and synced information with the associated
  org-note. (Besides the note content, each annotate will record the IDs of the
  corresponding org heading and potentially even it's parent org heading, such
  that tree-rebuild is possible.)

My config in ~doom-emacs~:

#+BEGIN_SRC elisp
(use-package! org-noter
  :commands (org-noter)
  :config
  (require 'org-noter-pdftools)
  (after! pdf-tools
    (setq pdf-annot-activate-handler-functions #'org-noter-pdftools-jump-to-note))
  (setq org-noter-notes-mode-map (make-sparse-keymap)))

(use-package! org-pdftools
  :init (setq org-pdftools-search-string-separator "??")
  :config
  (after! org
    (org-link-set-parameters "pdftools"
                             :follow #'org-pdftools-open
                             :complete #'org-pdftools-complete-link
                             :store #'org-pdftools-store-link
                             :export #'org-pdftools-export)
    (add-hook 'org-store-link-functions 'org-pdftools-store-link)))
#+END_SRC

If you are not using ~doom-emacs~, simply change ~use-package!~ to ~use-package~ and ~after!~ to ~with-eval-after-load~.

* Planed features
This is the first step of a set of overhauls of Emacs PDF notetaking experience.
The features below are planned (either in this package or as PR to other
packages):
- [ ] Optionally grab image/text excerpt from the PDF and insert below the
  corresponding org-heading.
- [ ] Link export with image/text-based excerpt from the PDF.
- [ ] (Long-term) Org <-> PDF Annotation converter.
